
# Project information

site_name: SORMAS Glossary
repo_name: 'hzi-braunschweig/SORMAS-Glossary'
repo_url: 'https://github.com/hzi-braunschweig/SORMAS-Glossary'


# Configuration
theme:
  name: null
  custom_dir: material


  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo


# Customization
extra:
  alternate:
    - name: English
      link: https://hzi-braunschweig.github.io/SORMAS-Glossary/en/
      lang: en
    - name: Français
      link: https://hzi-braunschweig.github.io/SORMAS-Glossary/fr/
      lang: fr
    - name: Deutsch
      link: https://hzi-braunschweig.github.io/SORMAS-Glossary/de/
      lang: de

  social:
  - icon: fontawesome/brands/github
    link: https://github.com/hzi-braunschweig/SORMAS-Glossary
