site_name: SORMAS Glossary
repo_name: 'hzi-braunschweig/SORMAS-Glossary'
repo_url: 'https://github.com/hzi-braunschweig/SORMAS-Glossary'

theme:
  name: material
  features:
  - tabs
extra:
  version: 0.10
  palette:
    primary: 'cyan'
  social:
  - icon: 'fontawesome/brands/github-alt'
    link: 'https://github.com/hzi-braunschweig/SORMAS-Glossary'
plugins:
- search:
    separator: '[\s]+'

nav:
- Home: "index.md"
- Dashboard: "dashboard_directory_ordered.md"
- Tasks Management: "task_amangement_directory_ordered.md"
- Case Management: "case_management.md"
