site_name: SORMAS Glossary
repo_name: 'hzi-braunschweig/SORMAS-Glossary'
repo_url: 'https://github.com/hzi-braunschweig/SORMAS-Glossary'

theme:
  name: material
  features:
  - tabs
extra:
  alternate:
    - name: English
      link: https://hzi-braunschweig.github.io/SORMAS-Glossary/en/
      lang: en
  version: 0.10
  palette:
    primary: 'cyan'
  social:
  - icon: 'fontawesome/brands/github-alt'
    link: 'https://github.com/hzi-braunschweig/SORMAS-Glossary'
plugins:
- search:
    separator: '[\s]+'

nav:
- Welcome: "en/index.md"
- Dashboard: "en/dashboard_directory_ordered.md"
- Tasks Management: "en/task_management_directory_ordered.md"
- Case Management: "en/case_management.md"
